// @generated by sqlay. Do not edit.

import type { FixtureAmount, FixtureLabel, QualifiedChildLabel } from "@fixtures/domain-types";

type SqlParam = unknown;

export type typeMappingOverrides_Input = {
  minimumAmount: FixtureAmount;
  parentId: number;
};

export type typeMappingOverrides_Row = {
  idNumber: number;
  decimalNumber: number;
  enumState: "one" | "two";
  nullableEnumState: "one" | "two" | null;
  setFlags: string;
  fixtureLabel: FixtureLabel;
  nullableFixtureLabel: FixtureLabel | null;
  builderLocalAmount: FixtureAmount | null;
  qualifiedChildLabel: QualifiedChildLabel;
};

export type typeMappingOverrides_Output = typeMappingOverrides_Row | null;

export function typeMappingOverrides(
  input: typeMappingOverrides_Input,
): { sql: string; params: readonly [FixtureAmount, number] } {
  return {
    sql: "\nSELECT\n  p.bigint_nn_col AS idNumber,\n  p.decimal_18_4_nn_col AS decimalNumber,\n  p.enum_nn_col AS enumState,\n  p.enum_col AS nullableEnumState,\n  p.set_nn_col AS setFlags,\n  p.varchar_255_nn_col AS fixtureLabel,\n  p.varchar_255_col AS nullableFixtureLabel,\n  p.decimal_18_4_col AS builderLocalAmount,\n  c.varchar_32_nn_col AS qualifiedChildLabel\nFROM fixture_all_column_type AS p\nINNER JOIN sqlay.fixture_child AS c\n  ON c.parent_bigint_nn_col = p.bigint_nn_col\nWHERE p.decimal_18_4_nn_col >= ?\n  AND p.bigint_nn_col = ?\nLIMIT 1;\n\n",
    params: [input.minimumAmount, input.parentId] as const,
  };
}

export type typeMappingOverrideRows_Input = {
  rows: readonly [{ childId: number; parentId: number; childLabel: QualifiedChildLabel; childAmount: FixtureAmount }, ...{ childId: number; parentId: number; childLabel: QualifiedChildLabel; childAmount: FixtureAmount }[]];
};

export function typeMappingOverrideRows(
  input: typeMappingOverrideRows_Input,
): { sql: string; params: readonly SqlParam[] } {
  const sqlParts: string[] = [];
  const params: SqlParam[] = [];

  if (input.rows.length === 0) {
    throw new Error("Repeat `rows` requires at least one item");
  }

  sqlParts.push("\nINSERT INTO sqlay.fixture_child (\n  child_bigint_nn_col,\n  parent_bigint_nn_col,\n  varchar_32_nn_col,\n  decimal_12_2_nn_col\n) VALUES\n");
  {
    let repeatIndex = 0;
    for (const repeatItem of input.rows) {
      if (repeatIndex > 0) {
        sqlParts.push(",");
      }
      sqlParts.push("\n(\n  ?,\n  ?,\n  ?,\n  ?\n)\n");
      params.push(repeatItem.childId);
      params.push(repeatItem.parentId);
      params.push(repeatItem.childLabel);
      params.push(repeatItem.childAmount);
      repeatIndex += 1;
    }
  }
  sqlParts.push(";\n\n");

  return {
    sql: sqlParts.join(""),
    params,
  };
}

export type typeMappingOverrideSlotSearch_Input = {
  labelFilter?: {
    $fragment: "typeMappingFixtureLabel";
    fixtureLabel: FixtureLabel;
  };
};

export type typeMappingOverrideSlotSearch_Row = {
  idNumber: number;
  enumState: "one" | "two";
};

export type typeMappingOverrideSlotSearch_Output = typeMappingOverrideSlotSearch_Row[];

export function typeMappingOverrideSlotSearch(
  _input: typeMappingOverrideSlotSearch_Input = {},
): { sql: string; params: readonly SqlParam[] } {
  const sqlParts: string[] = [];
  const params: SqlParam[] = [];

  sqlParts.push("\nSELECT\n  p.bigint_nn_col AS idNumber,\n  p.enum_nn_col AS enumState\nFROM fixture_all_column_type AS p\nWHERE p.bigint_nn_col IS NOT NULL\n");
  switch (_input.labelFilter?.$fragment) {
    case "typeMappingFixtureLabel":
      sqlParts.push("\nAND p.varchar_255_nn_col = ?\n\n");
      params.push(_input.labelFilter.fixtureLabel);
      break;
  }
  sqlParts.push("\nORDER BY p.bigint_nn_col;\n");

  return {
    sql: sqlParts.join(""),
    params,
  };
}
