name: "[format] Check (Reusable Workflow)"

on:
  workflow_call:
    inputs:
      dprint-version:
        description: dprint CLI version used by CI.
        required: false
        type: string
        default: 0.54.0

permissions:
  contents: read

jobs:
  dprint:
    name: dprint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup dprint
        uses: ./.github/actions/setup-dprint
        with:
          version: ${{ inputs.dprint-version }}

      - name: Check formatting
        run: dprint check
