name: "[sqlite-fixtures] Push"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sqlite-fixtures:
    name: Call SQLite fixtures check
    uses: ./.github/workflows/_sqlite-fixtures-check.yml
